# fabric-network/docker-compose-fabric.yaml

version: '3.7'

networks:
  swarm-network: # Custom network, same as used by Python apps
    external: true # Assumes this network is created by docker-compose.yaml

services:
  # Certificate Authority for Techcombank
  ca.techcombank.example.com:
    container_name: ca.techcombank.example.com
    image: hyperledger/fabric-ca:latest
    hostname: ca.techcombank.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-techcombank
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      # Adjustments to TLS cert/key paths for CA:
      # These files are typically found directly under the CA's home directory within the container
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem # Common CA cert name
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/ca-key.pem # Common CA key name
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw --cfg.identities.allowremove'
    volumes:
      # This volume mount should point to the CA's specific crypto material generated by cryptogen
      # It typically maps the 'ca' directory which contains the ca-cert.pem and ca-key.pem
      - ./crypto-config/peerOrganizations/techcombank.example.com/ca/:/etc/hyperledger/fabric-ca-server/
    networks:
      - swarm-network

  # Orderer Node
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:latest
    hostname: orderer.example.com
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # TLS settings
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      # Consolidated TLS_ROOTCAS - orderer's own TLS CA root certificate
      # It's usually just its own tlscacerts, not its general CA cert and its TLS CA cert separately like this.
      # The tlsca.example.com-cert.pem is enough here, as it's the root for TLS.
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/tlscacerts/tlsca.example.com-cert.pem] # Adjusted path
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:17050 # Health check endpoint
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls
      # Removed redundant/potentially confusing TLS CA mount.
      # The /var/hyperledger/orderer/tls volume mount already includes tlscacerts.
      # - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/tlsroot.pem:/var/hyperledger/orderer/tls/ca.crt
    ports:
      - "7050:7050"
      - "17050:17050"
    networks:
      - swarm-network

  # CouchDB for peer0.techcombank.example.com
  couchdb0:
    container_name: couchdb0
    image: couchdb:3.3.2 # Use a recent CouchDB version
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984" # For debugging/monitoring CouchDB state
    networks:
      - swarm-network

  # Peer for Techcombank
  peer0.techcombank.example.com:
    container_name: peer0.techcombank.example.com
    image: hyperledger/fabric-peer:latest
    hostname: peer0.techcombank.example.com
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=swarm-network # Link to common network
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      # Corrected Peer TLS Root Cert file path to be consistent with cryptogen output
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tlscacerts/tlsca.techcombank.example.com-cert.pem # Adjusted for consistency
      - CORE_PEER_ID=peer0.techcombank.example.com
      - CORE_PEER_ADDRESS=peer0.techcombank.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.techcombank.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.techcombank.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.techcombank.example.com:7051
      - CORE_PEER_LOCALMSPID=TechcombankMSP # CHANGED: MSP ID
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:17051 # Health check endpoint
      # CouchDB configuration for state database
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock # Mount Docker socket for chaincode deployment
      - ./crypto-config/peerOrganizations/techcombank.example.com/peers/peer0.techcombank.example.com/msp:/etc/hyperledger/fabric/msp # CHANGED: Path to peer MSP
      - ./crypto-config/peerOrganizations/techcombank.example.com/peers/peer0.techcombank.example.com/tls:/etc/hyperledger/fabric/tls # CHANGED: Path to peer TLS certs
      - ./crypto-config/peerOrganizations/techcombank.example.com/peers/peer0.techcombank.example.com:/var/hyperledger/production # CHANGED: Persistent ledger data
    ports:
      - "7051:7051"
      - "7052:7052" # Chaincode port
      - "17051:17051"
    depends_on:
      - orderer.example.com
      - couchdb0
    networks:
      - swarm-network
